<?php if (!defined('ABSPATH')) exit; ?>
<div class="wrap ai-mh-admin">
    <h1><?php _e( 'Chat History & Leads', 'akarai-customer-service' ); ?></h1>
    <p><?php _e( 'Review your conversations and the leads generated by AkarAi.', 'akarai-customer-service' ); ?></p>

    <div class="ai-mh-card">
        <table class="wp-list-table widefat fixed striped">
            <thead>
                <tr>
                    <th><?php _e( 'Visitor / Lead', 'akarai-customer-service' ); ?></th>
                    <th><?php _e( 'Contact info', 'akarai-customer-service' ); ?></th>
                    <th><?php _e( 'Messages', 'akarai-customer-service' ); ?></th>
                    <th><?php _e( 'Start Date', 'akarai-customer-service' ); ?></th>
                    <th><?php _e( 'Status', 'akarai-customer-service' ); ?></th>
                    <th style="width: 100px;"><?php _e( 'Action', 'akarai-customer-service' ); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php if ($conversations): foreach ($conversations as $conv): ?>
                <tr>
                    <td><strong><?php echo esc_html($conv->name . ' ' . $conv->surname); ?></strong></td>
                    <td><?php echo esc_html($conv->phone); ?></td>
                    <td><?php echo intval($conv->msg_count / 2); // Simple pair count ?> <?php _e( 'Exchange', 'akarai-customer-service' ); ?></td>
                    <td><?php echo $conv->started_at; ?></td>
                    <td><span class="badge"><?php echo esc_html($conv->status); ?></span></td>
                    <td>
                        <a href="<?php echo admin_url('admin.php?page=akarai-cs-conversations&conv_id=' . $conv->id); ?>" class="button button-small"><?php _e( 'Review', 'akarai-customer-service' ); ?></a>
                    </td>
                </tr>
                <?php endforeach; else: ?>
                <tr>
                    <td colspan="6"><?php _e( 'No conversations found yet.', 'akarai-customer-service' ); ?></td>
                </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>
